spring.application.name=secure-api

spring.datasource.url=jdbc:mysql://localhost:3306/secure_api_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.expiration-minutes=30
jwt.output-file=generated-jwts.txt
jwt.output-max-entries=5
